version: '3'

services:
  mobile-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    environment:
      - NODE_ENV=development
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - EXPO_DOCKER_BACKEND_URL=http://backend:8000
      - EXPO_TUNNEL=true
      - DEBUG=true
    volumes:
      - .:/app
      - /app/node_modules
