version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: practice-app-db
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: practice-app-backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py create_waste_test_data &&
             python manage.py create_test_goal_templates &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      # Override the DATABASE_URL
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/practice_app_db
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend-web
      dockerfile: Dockerfile
      args:
         - REACT_APP_SITE_URL=http://localhost:3000
         - REACT_APP_API_URL=http://localhost:8000/api
         - REACT_APP_GITHUB_CLIENT_ID=Ov23liAeCX9IBhrPJ1ML
         - REACT_APP_GCP_CLIENT_ID=115929609709-p3955grkice5ka8ul4m37uoce3bs53v2.apps.googleusercontent.com
    container_name: practice-app-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend-web/.env
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:

