# URL patterns for the user app (v1)

from django.urls import path, include 
from rest_framework.routers import DefaultRouter 
from .views import UserProfileView, UserViewSet 

# Consider adding app_name = 'user_api_v1' if using namespaces

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'users', UserViewSet, basename='user') 

urlpatterns = [
    # Endpoint for the current user's profile
    path('me/', UserProfileView.as_view(), name='user-profile'),
    # Include the routes generated by the router (for admin user management)
    path('', include(router.urls)),
]
