# Generated by Django 4.2.20 on 2025-12-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_remove_wastelog_disposal_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastelog',
            name='disposal_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
