# Generated by Django 4.2.20 on 2025-05-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            # Drop the duplicate column if it exists
            sql='ALTER TABLE authentication_userauthtoken DROP COLUMN IF EXISTS user_id;',
            reverse_sql='',  # No reverse operation needed
        ),
    ]
