# Generated by Django 4.2.20 on 2025-11-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_oauth_user_alter_userauthtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('github', 'GitHub')], max_length=50),
        ),
    ]
