# Generated by Django 4.2.20 on 2025-12-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
