# Generated by Django 4.2.20 on 2025-12-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_is_anonymous'),
        ('user', '0002_rename_profile_picture_to_url'),
    ]

    operations = [
    ]
