blank_issues_enabled: true
contact_links:
  - name: documentation
    url: https://github.com/bounswe/bounswe2025group3/tree/main/.github/ISSUE_TEMPLATE/documentation.md
    about: If you want to contribute to the documentation page
  - name: sequence-diagram
    url: https://github.com/bounswe/bounswe2025group3/tree/main/.github/ISSUE_TEMPLATE/sequenceDiagram.yaml
    about: Please use this template to create an issue for sequence diagram
