# Generated by Django 4.2.20 on 2025-12-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_duration_event_equipment_needed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='equipment_needed',
        ),
    ]
