# Generated by Django 4.2.20 on 2025-05-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('target', models.FloatField()),
                ('progress', models.FloatField(default=0.0)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, help_text='Start date for custom timeframe goals', null=True)),
                ('status', models.CharField(default='active', help_text='Status of the goal (e.g., active, achieved, failed)', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GoalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target', models.FloatField(help_text='Target value the user should aim to reach')),
                ('timeframe', models.CharField(help_text="Timeframe description (e.g., 'weekly', 'monthly')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
