# Generated by Django 4.2.20 on 2025-05-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date for custom timeframe goals', null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date for custom timeframe goals', null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(default='active', help_text='Status of the goal (e.g., active, achieved, failed)', max_length=20),
        ),
    ]
