# Generated by Django 4.2.20 on 2025-05-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
        ('goals', '0002_goal_end_date_goal_start_date_goal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_type',
        ),
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.subcategory'),
        ),
        migrations.AlterField(
            model_name='goaltemplate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_templates', to='waste.subcategory'),
        ),
    ]
