# Generated by Django 4.2.20 on 2025-10-20 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goaltemplate',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the template starts (defaults to creation date)'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the goal starts (defaults to creation date)'),
        ),
    ]
